### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by elig0n** [RomanKornev/Calculator#2]
Can you add bases conversions (ie, binary, hex, oct ) ?

**Comment by RomanKornev** [comment]
It already has all the conversions. 
To convert hex, bin, oct to to base10 just prefix the number with 0x, 0b, 0o respectively:
`0x10c ` : `0x10c = 268`
`0b101 ` : `0b101 = 5`
etc...

To convert it back just use the builtin Python functions 
`hex(256) ` : `hex(256) = 0x100`
`bin(256) ` : `bin(256) = 0b100000000`
`oct(256) ` : `oct(256) = 0o400`

To use any other base use `int(str, base)`:
`int('410', 5)` : `int('410', 5) = 105`
